# Generated by Django 2.0.2 on 2018-03-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web', models.CharField(max_length=300)),
                ('passwd', models.CharField(max_length=30)),
                ('count', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=300)),
            ],
        ),
    ]
